
#Kubeconfig file
#this file consist Define 2 clusters, users, and 3 contexts



apiVersion: v1
kind: Config
current-context: dev-user@google   #name here for check which kubecluster
preferences: {}


#Part 1
clusters:           #two clusters, one for development work and one for scratch work
- name: development1
  cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt   ##everywhere here use fullpathh
    server: https://my-kube-demoproject:6443
  

- cluster:
  name: scratch

#Part 2
users:
- name: developer-kube1
  user:
    client-certificate: /etc/kubernetes/pki/users/admin.crt
    client-key: /etc/kubernetes/pki/users/admin.crt   #everywhere here use fullpath
- name: experimenter


#Part 3
contexts:
- name: dev-frontend
  context:
    cluster: development1  #same name here same as Cluster
    user: developer-kube1   #same name here same as User
    namespace: finance      #this use for name space of cluster
  
- context:
  name: dev-storage
- context:
  name: exp-scratch


  ## Kubectl config modify file 

  ##--->  kubectl config view     # this command to view config file
  
