apiVersion: v1    #also we can use apps/v1beta2 when change kind
kind: Pod   #name of task like deployement - apps/v1, Pod - v1, service - v1 , ReplicaSet - apps/v1
metadata:
  name: nginx-deployement
spec:
  selector:
    matchLables:
      app: nginx
  replicas: 2  #tells deployement to run 2 pods matching template    
  template:
    metadata:
      lables:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80



