##POD_config_secrets_in_kubernetes

##config_maps_in_kubernetes_file
apiVersion: v1
kind: Secret
metdata:
    name: app-secret
data:
    DB_Host: mysql    #this all host,user and pass convert bash 64 to convert
    DB_User: root
    DB_password: paswrdddd
          


##Run this file use bellow #Command

#       kubectl create -f confi_secret_in_kubernetes.yaml
##View Config Map

 #      kubectl get secret
 #secrets Description details command

 #      kubectl describe secrets

###get secret fiel yaml encoded format  

#       kubectl get secret app-secret -o yaml




 
     ##Default commnad 1:
        
#        kubectl create secret generic <secret-name> --from-literal=<key>=<value>

##Command 1:
        
#        kubectl create secret generic \ app-secret  
#                                    --from-literal=DB_HOST=mysql
#                                    --from-literal=DB_User=root
#                                     --from-literal=DB_password=paswordddd


#Command 3: 

#        kubectl create secret generic <secret-name> --from-file=<path-of-file>


#kubectl create secret generic \ app-secret --from-file=app_secret.properties






